#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinFloatingActionButton.Resource", IsApplication=false)]

namespace XamarinFloatingActionButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public static int fab_addButtonColorNormal = 2130771977;
			
			// aapt resource value: 0x7f010008
			public static int fab_addButtonColorPressed = 2130771976;
			
			// aapt resource value: 0x7f01000b
			public static int fab_addButtonPlusIconColor = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public static int fab_addButtonSize = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public static int fab_addButtonStrokeVisible = 2130771980;
			
			// aapt resource value: 0x7f010001
			public static int fab_colorDisabled = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int fab_colorNormal = 2130771970;
			
			// aapt resource value: 0x7f010000
			public static int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public static int fab_expandDirection = 2130771983;
			
			// aapt resource value: 0x7f010003
			public static int fab_icon = 2130771971;
			
			// aapt resource value: 0x7f01000d
			public static int fab_labelStyle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public static int fab_labelsPosition = 2130771982;
			
			// aapt resource value: 0x7f010007
			public static int fab_plusIconColor = 2130771975;
			
			// aapt resource value: 0x7f010004
			public static int fab_size = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int fab_stroke_visible = 2130771974;
			
			// aapt resource value: 0x7f010005
			public static int fab_title = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f030008
			public static int fab_actions_spacing = 2130903048;
			
			// aapt resource value: 0x7f030002
			public static int fab_icon_size = 2130903042;
			
			// aapt resource value: 0x7f030009
			public static int fab_labels_margin = 2130903049;
			
			// aapt resource value: 0x7f030003
			public static int fab_plus_icon_size = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int fab_plus_icon_stroke = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int fab_shadow_offset = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int fab_shadow_radius = 2130903046;
			
			// aapt resource value: 0x7f030001
			public static int fab_size_mini = 2130903041;
			
			// aapt resource value: 0x7f030000
			public static int fab_size_normal = 2130903040;
			
			// aapt resource value: 0x7f030007
			public static int fab_stroke_width = 2130903047;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int fab_bg_mini = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int fab_bg_normal = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040006
			public static int down = 2130968582;
			
			// aapt resource value: 0x7f040000
			public static int fab_expand_menu_button = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int fab_label = 2130968577;
			
			// aapt resource value: 0x7f040004
			public static int left = 2130968580;
			
			// aapt resource value: 0x7f040002
			public static int mini = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int normal = 2130968579;
			
			// aapt resource value: 0x7f040005
			public static int right = 2130968581;
			
			// aapt resource value: 0x7f040007
			public static int up = 2130968583;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AddFloatingActionButton = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public static int AddFloatingActionButton_fab_plusIconColor = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public static int FloatingActionButton_fab_colorDisabled = 1;
			
			// aapt resource value: 2
			public static int FloatingActionButton_fab_colorNormal = 2;
			
			// aapt resource value: 0
			public static int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public static int FloatingActionButton_fab_icon = 3;
			
			// aapt resource value: 4
			public static int FloatingActionButton_fab_size = 4;
			
			// aapt resource value: 6
			public static int FloatingActionButton_fab_stroke_visible = 6;
			
			// aapt resource value: 5
			public static int FloatingActionButton_fab_title = 5;
			
			public static int[] FloatingActionsMenu = new int[] {
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public static int FloatingActionsMenu_fab_addButtonColorNormal = 1;
			
			// aapt resource value: 0
			public static int FloatingActionsMenu_fab_addButtonColorPressed = 0;
			
			// aapt resource value: 3
			public static int FloatingActionsMenu_fab_addButtonPlusIconColor = 3;
			
			// aapt resource value: 2
			public static int FloatingActionsMenu_fab_addButtonSize = 2;
			
			// aapt resource value: 4
			public static int FloatingActionsMenu_fab_addButtonStrokeVisible = 4;
			
			// aapt resource value: 7
			public static int FloatingActionsMenu_fab_expandDirection = 7;
			
			// aapt resource value: 5
			public static int FloatingActionsMenu_fab_labelStyle = 5;
			
			// aapt resource value: 6
			public static int FloatingActionsMenu_fab_labelsPosition = 6;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
